### ISSUE TITLE
unification vs matching

### ISSUE THREAD

**Issue by majidaldo** [pythological/unification#20]
```
from unification import unifiable, var
from unification.match import match 
import attr

@unifiable
@attr.s(frozen=True)
class A:
    a= attr.ib(default=var('a'))

@match(A(4))
def f(obj):
    return 'four'

@match(A(3))
def f(obj):
    return 'three'

@match(A())
def f(obj):
    return 'variable'


if __name__ == "__main__":
    print(f(A()))
    print(f(A(3)))
```

This works as you'd expect for ` f(A())`, and `f(A(3))`. However, `f(A())` does not work as expected when A is `unifiable`. Also, obviously you can't `unify` `A` with anything. Am I missing something or is this expected?

**Comment by brandonwillard** [comment]
The example doesn't compile; is there a typo somewhere?

**Comment by majidaldo** [comment]
> The example doesn't compile; is there a typo somewhere?

just copypasted. it's not even deterministic.

**Comment by majidaldo** [comment]
Also, looking at the funcs, like `for s,f in f.funcs.items(): print(s,f)`, changes the result.

**Comment by brandonwillard** [comment]
It looks like `f(A())` is effectively trying the three available dispatch unification patterns (i.e. `A(4)`, `A(3)`, and `A(var())`) using an [ordering](https://github.com/pythological/unification/blob/master/unification/match.py#L120) based on the specificity of the patterns (i.e. greatest specificity to least).  

In your example, the argument `A()` will unify with all of those dispatch patterns (recall that `A() == A(var())`, by definition), so the first successful unification is returned and that is the function assigned to the pattern `A(3)`.

If said ordering put the `A(var())` dispatch pattern first, then `A(3)` and `A(4)` would never be dispatched, because `A(var())` will unify with all `A(...)`.

**Comment by brandonwillard** [comment]
I'm going to close this, but feel free to continue asking questions if you have any.
