### ISSUE TITLE
how to not unify with None?

### ISSUE THREAD

**Issue by majidaldo** [pythological/unification#26]
Is there a clean way to not unify with `None` (w/o processing the substitutions)?

**Comment by brandonwillard** [comment]
The best way to _not_ unify with something will almost always involve using a form that naturally excludes said thing.

Otherwise, you can always implement a case for `None` in the dispatch function `_unify`.  

N.B., whatever you change about `_unify` should be complemented by corresponding changes to `_reify`.

**Comment by majidaldo** [comment]
Is there some mathy reason for the current behavior?? For me, it's 'common sense' that you can never equalize x and None if x is thought to be as something that 'exists'.

**Comment by brandonwillard** [comment]
We're doing _syntactic unification_, and, in the context of Python, `None` is just another constant symbol in the language.  If `x` is a variable, `x` should unify with any term&mdash;including `None`.  Besides a variable, `None` only unifies with `None`.
